# Generated by Django 4.2.5 on 2024-10-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='is_received',
            field=models.BooleanField(default=True),
        ),
    ]
